### ISSUE TITLE
Completion for jedi isn't showing

### ISSUE THREAD

**Issue by tony** [zchee/deoplete-jedi#13]
Continued from https://github.com/Shougo/deoplete.nvim/issues/197

``python-client`` is ``neovim-0.1.3``.

[log_68422.txt](https://github.com/zchee/deoplete-jedi/files/156703/log_68422.txt)

```
# freebsd-version -ku; uname -apKU                            
11.0-CURRENT
11.0-CURRENT
FreeBSD z600 11.0-CURRENT FreeBSD 11.0-CURRENT #56: Tue Mar  1 18:52:01 CST 2016     root@z600:/usr/obj/usr/src/sys/MYKERNEL  amd64 amd64 1100100 1100099

# nvim --version
NVIM 0.1.2
Build type: Release
Compilation: /usr/bin/cc -O2 -pipe -fstack-protector -fno-strict-aliasing -Wconversion -O2 -pipe -fstack-protector -fno-strict-aliasing -DDISABLE_LOG -Wall -We
xtra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/wrkdirs/usr/ports/editors/neovim/work/neovim-b33c777/config -I/wrkdirs/usr/ports/editors/neovim/work/neovim-b33c777/src -I/usr/local/include -I/usr/local/include -I/usr/local/include/luajit-2.0 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/include -I/wrkdirs/usr/ports/editors/neovim/work/neovim-b33c777/src/nvim/auto -I/wrkdirs/usr/ports/editors/neovim/work/neovim-b33c777/include                                  Compiled by root@head-amd64-default-job-19

Optional features included (+) or not (-): +acl   +iconv    -jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

```

minimal vim config:

```viml
" Your minimal init.vim

set runtimepath+=~/.vim/bundle/deoplete.nvim/
set runtimepath+=~/.vim/bundle/deoplete-jedi/

" deoplete.vim
" credit: https://gist.github.com/zchee/c314e63ae8b6bea50bb4
let g:deoplete#enable_at_startup = 1
set completeopt+=noinsert
set completeopt-=preview
let g:deoplete#enable_ignore_case = 'ignorecase'
let g:deoplete#auto_completion_start_length = 0
let g:min_pattern_length = 0
" https://github.com/Shougo/deoplete.nvim/issues/117

let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer', 'vim', 'member']
let g:deoplete#sources#go = 'vim-go'

inoremap <expr><C-n> deoplete#mappings#manual_complete()

if exists(':DeopleteEnable')
  let g:jedi#completions_enabled = 0
  let g:jedi#auto_vim_configuration = 0
  let g:jedi#smart_auto_mappings = 0
  let g:jedi#show_call_signatures = 0
endif
```

**Comment by Shougo** [comment]
@tony Please upload the reproduce ways from starting.

```vimif exists(':DeopleteEnable')
  let g:jedi#completions_enabled = 0
  let g:jedi#auto_vim_configuration = 0
  let g:jedi#smart_auto_mappings = 0
  let g:jedi#show_call_signatures = 0
endif
```

Not needed lines.

> let g:deoplete#enable_ignore_case = 'ignorecase'

`let g:deoplete#enable_ignore_case = 1` is correct.

> let g:min_pattern_length = 0

Invalid option.

And normal deoplete completions works?

**Comment by tony** [comment]
No output at all for jedi. 

For normal files, with the following config you won't get any completion since it ignores buffer, vim and member sources.

deoplete.nvim is  51f3b0d9ed2100ac3f9a9df35ac22b4fd2feeefd

```viml
" Your minimal init.vim

set runtimepath+=~/.vim/bundle/deoplete.nvim/
set runtimepath+=~/.vim/bundle/deoplete-jedi/

" deoplete.vim
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1 
let g:deoplete#auto_completion_start_length = 0

let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer', 'vim', 'member']

inoremap <expr><C-n> deoplete#mappings#manual_complete()
```

[log_7667.txt](https://github.com/zchee/deoplete-jedi/files/158154/log_7667.txt)

So to be sure I created a bare bones configuration:

```viml
" Your minimal init.vim

set runtimepath+=~/.vim/bundle/deoplete.nvim/
set runtimepath+=~/.vim/bundle/deoplete-jedi/

" deoplete.vim
let g:deoplete#enable_at_startup = 1

inoremap <expr><C-n> deoplete#mappings#manual_complete()
```

This does show deoplete on regular files.

It does not show jedi-powered completions for python, only members. ``[m]``

[log_9111.txt](https://github.com/zchee/deoplete-jedi/files/158157/log_9111.txt)

**Comment by tony** [comment]
To be sure I updated to  https://github.com/Shougo/deoplete.nvim/commit/43823d522f2d54ac196a5a7628da0a3c271d6712, same config:

```viml
" Your minimal init.vim

set runtimepath+=~/.vim/bundle/deoplete.nvim/
set runtimepath+=~/.vim/bundle/deoplete-jedi/

" deoplete.vim
let g:deoplete#enable_at_startup = 1

inoremap <expr><C-n> deoplete#mappings#manual_complete()
```

[log_11625.txt](https://github.com/zchee/deoplete-jedi/files/158161/log_11625.txt)

No jedi completion :(

**Comment by Shougo** [comment]
@tony 

I cannot reproduce the problem.

```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/deoplete-jedi/

let g:deoplete#enable_at_startup = 1
let g:deoplete#max_list = 10
let g:deoplete#enable_refresh_always = 1
```

I think your Python environments is something wrong.
Can you test it in other environments?

**Comment by Shougo** [comment]
Please update neovim, deoplete, deoplete-jedi to the latest version.
neovim 0.12 is not latest version.

**Comment by tony** [comment]
> please update neovim

build from git master?

**Comment by Shougo** [comment]
Yes.

**Comment by Shougo** [comment]
How do you clone deoplete-jedi?
It uses submodule feature.  Simple `git clone` does not work.

You must use `git clone --recursive`.

**Comment by tony** [comment]
I use plug.  Also, I'm having the same behavior happen for deoplete-go. I will make a seperate issue for that.

Updated neovim:

```
# vim --version 
NVIM v0.1.3-312-g0e9f7a7
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wno-c11-extensions -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/usr/home/tony/study/vim/neovim/build/config -I/usr/home/tony/study/vim/neovim/src -I/usr/home/tony/study/vim/neovim/.deps/usr/include -I/usr/home/tony/study/vim/neovim/.deps/usr/include -I/usr/home/tony/study/vim/neovim/.deps/usr/include/luajit-2.0 -I/usr/home/tony/study/vim/neovim/.deps/usr/include -I/usr/home/tony/study/vim/neovim/.deps/usr/include -I/usr/home/tony/study/vim/neovim/.deps/usr/include -I/usr/home/tony/study/vim/neovim/.deps/usr/include -I/usr/local/include -I/usr/include -I/usr/home/tony/study/vim/neovim/build/src/nvim/auto -I/usr/home/tony/study/vim/neovim/build/include
Compiled by root@z600

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

Using neovim 0.1.3 client.

```viml

set runtimepath+=~/.vim/bundle/deoplete.nvim/
set runtimepath+=~/.vim/bundle/deoplete-jedi/


let g:deoplete#enable_at_startup = 1
let g:deoplete#max_list = 10
let g:deoplete#enable_refresh_always = 1
```

This time there was no virtual environment. Both neovim for python 2 and 3 are updated to 0.1.3, and I'm just doing ``import os`` and ``import sys`` and trying to get completion.

[log_12887.txt](https://github.com/zchee/deoplete-jedi/files/159660/log_12887.txt)

**Comment by tony** [comment]
All above posts, including https://github.com/zchee/deoplete-jedi/issues/13#issuecomment-192564929 were on FreeBSD CURRENT. I also get the same results on Ubuntu.

Tested on Ubuntu:

```
tony@ubuntu:~/.vim/bundle$ uname -a
Linux ubuntu 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
tony@ubuntu:~/.vim/bundle$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
[log_14907.txt](https://github.com/zchee/deoplete-jedi/files/159667/log_14907.txt)

tony@ubuntu:~/.vim/bundle$ nvim --version
NVIM 0.1.3-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/build/config -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/src -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/.deps/usr/include -I/usr/include -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/build/src/nvim/auto -I/build/neovim-037Ah7/neovim-0.1.2ubuntu1+git201603011706+2338+17~ubuntu15.10.1/build/include
Compiled by buildd@lgw01-15

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

[log_15043.txt](https://github.com/zchee/deoplete-jedi/files/159671/log_15043.txt)

No virtualenv.  Just opening a file, for example ``hi.py`` and trying to do stand library completion.

```
tony@ubuntu:~/.vim/bundle$ python3 -c "import neovim"
tony@ubuntu:~/.vim/bundle$ python2 -c "import neovim"
tony@ubuntu:~/.vim/bundle$ python3 --version; python --version
Python 3.4.3+
Python 2.7.10

```

**Comment by tony** [comment]
Even golang isn't giving me anything. :[

Is anyone else here having a problem with completion in deoplete? If you do, please provide some information on your environment setup.

**Comment by tweekmonster** [comment]
@tony I'm having a similar issue using virtualenvs, but not sure if it's related to yours.

There seems to be a problem with Jedi and virtualenvs where performance degrades each time Jedi completions are evaluated.  The first time starting up nvim and completing `os.`, it takes about 1 second to list completions.  After repeating, it takes about 1 second longer than the last time it was completed.  Repeating this after a while, the delay is so long that it will seem like it's not doing any completions at all.

Without using a different virtualenv, the completions for `os.` no longer have this delay.  But, if I use the jedi-vim plugin with a different virtualenv, I don't have any delays when completing `os.`.  So, I'm confused about where to report this issue.

As for my environment, I'm using PyEnv to keep neovim packages separate using Python 2.7.9 and 3.4.3.  The completions were for a script that was using a Python 3.4.4 virtualenv.
```vim
let g:python_host_prog = '/home/tallen/.pyenv/versions/neovim2/bin/python'
let g:python3_host_prog = '/home/tallen/.pyenv/versions/neovim3/bin/python'
```

There are a couple of possible solutions I explored:

- Add an option to not evaluate Jedi completions.  Here is what I did to get nearly instant completions: https://github.com/tweekmonster/deoplete-jedi/commit/68bdbf0bf83f2881e7c47cf0d928ec17c08138d1  The problem is there's no nice formatting :sob:
- Downgrade Jedi to v0.8.1.  The completions take about 500ms to do completions for `os.` and it doesn't suffer from the degradation over time.  I don't know Jedi well enough to now what the drawbacks to this is.  Got this idea from this issue that hasn't been updated since 12/2015: https://github.com/davidhalter/jedi/issues/591
- Make the Jedi completions an external script that's called via subprocess and prints each completion on a line.  This resets Jedi on each call, but not ideal since there's overhead in starting a Python instance and parsing the lines.

**Comment by zchee** [comment]
@tony Sorry late reply :(
I'll comment and support later.

**Comment by tcuthbert** [comment]
I am also experiencing the same issue as @tweekmonster.

**Comment by zchee** [comment]
@tony @tcuthbert I can't fully understand your environment in this issue thread, this problem may not be resolved easily.
If you don't mind, Let's talk in gitter. https://gitter.im/zchee/deoplete-jedi
If we are both online, resolve of the problem is likely to be soon.

@tweekmonster 
> There seems to be a problem with Jedi and virtualenvs where performance degrades each time Jedi completions are evaluated.....

I have also developed completion of clang and go, but Jedi is certainly slow as compared to those.
(Jedi and my code, I do not know either is wrong.)

> Without using a different virtualenv, the completions for os. no longer have this delay. But, if I use the jedi-vim plugin with a different virtualenv, I don't have any delays when completing `os.`. So, I'm confused about where to report this issue.

I do not use `virtualenv`, so I do not understand the reason for why such behavior :(
I will try `virtualenv` environment later.

> Add an option to not evaluate Jedi completions. Here is what I did to get nearly instant completions: tweekmonster@68bdbf0 The problem is there's no nice formatting.

Jedi returns too many information than to completion engine in other languages.
I've format because did not like the long completion, but would have been slowed by it.

> Downgrade Jedi to v0.8.1. The completions take about 500ms to do completions for os. and it doesn't suffer from the degradation over time. I don't know Jedi well enough to now what the drawbacks to this is. Got this idea from this issue that hasn't been updated since 12/2015: davidhalter/jedi#591

It is very interesting information for me.
I will test downgraded Jedi.

**Comment by zchee** [comment]
Incidentally, I wrote the first python for deoplete source, So implementation of the python does not yet understand :(

**Comment by tweekmonster** [comment]
@zchee No problem, it works fairly well :)

I actually found a way to speed up the completions.  Here's what I did to get faster completions: https://github.com/tweekmonster/deoplete-jedi/commit/5078396a238868702aa0de12cd90287b0eef0ef0

The problem is with Jedi's recursions, but I don't know exactly why it's a problem specifically with virtualenvs.  When a completion begins for a partial word, such as `os` the max recursion limit of 250 causes this completion to take about 1+ second.  If you continue to type `osc` (I was developing with django-oscar which encourages a * import), you will now have a completion that's waiting for the previous one to finish.  If you type out `oscar` fast enough, you will end up with 5 queued completions taking about 1+ second each.  I think the slowness here is because Jedi is searching for matches in the source file and all of its imports for a partial word match.

If you do an attribute completion with `.` it's reasonably fast even with the default max recursion of 250 since the search scope is less broad.

I think it can become faster if https://github.com/Shougo/deoplete.nvim/issues/204 gets added to deoplete since the completions will trigger once when the user stops typing instead of triggering on each key press.

**Comment by tweekmonster** [comment]
@zchee I created a docker image to reproduce the issue.  Maybe you will have a better idea of how to resolve it once you see the issue.  It's setup to be similar to the environment I'm using: Neovim using pyenv installations, but the shell using a Python version that has a lot of modules installed, and a different version from what Neovim is usinig.  Run it with:

```shell
docker run -it --rm tweekmonster/deoplete-jedi-issue
```

It will auto-start neovim with a Python script that will cause the issue.  The script has instructions on how to reproduce.  After you quit, you will have an option to display the debug logs.

The image takes a while to build, but if you prefer to build it yourself, you can inspect it here: https://github.com/tweekmonster/deoplete-jedi/tree/issue-reproduction/docker-testing

I think the main issue is that this plugin is getting completions for global variables.  It looks like jedi-vim is providing completions for modules and only displays buffer tags for everything else.

**Comment by zchee** [comment]
@tweekmonster Thanks! That good idea and I'm familiar with the Docker :)
I check it, and will consider to resolve way.

**Comment by zchee** [comment]
@tweekmonster FYI, I tried downgrade Jedi, but There was not much change is a simple profiler :(
I again try to find the cause of the problems that occur in the difference between the Jedi version.

**Comment by tweekmonster** [comment]
Yeah the downgrade only improved the global scope completions.  The new deoplete option to delay completion helps to keep the problem from piling up.  I set it 100ms and it has been working pretty well but still has a 1s+ delay.  It's mainly the global scope completions that's slow.  If you set `jedi.settings.max_executions` to 1, the results are instant, but the descriptions aren't accurate.  I didn't submit a PR for it because I wasn't sure if I was only fixing my specific situation.

**Comment by zchee** [comment]
@tweekmonster I understand.
I'll try to reproduce your situation.
And if this setting is useful workaround, I adding `jedi.config` and describe to README.md.

**Comment by zchee** [comment]
@tweekmonster I have tested a little bit, this is a very, very! slow :scream: 
CPU is rampage now lol

`issue-reproduction` is tested, I'll try to `faster-jedi-completion` or `faster-completion` branch also test comparison continues.

BTW, As I wrote before, because I usually do not write a python, it installed directly to `site-packages` without using the virtualenv.
In this case, jedi will be a little faster rather than sample docker container.
It would like to check if as well in your environment.

===

FYI, I use OS X, so **not native** docker.
but use OS X Kernel Hypervisor,  I think there is no impact.
Use it https://github.com/zchee/docker-machine-driver-xhyve.

**Comment by tweekmonster** [comment]
@zchee I don't think using docker-machine changes the results since it takes more than 500ms to do completions even on a native machine.

I'm finally getting a better understanding of deoplete's completion calls.  We can cache module resluts to get significant speed improvements since Jedi doesn't filter those.  It'll probably need to check for project files that have changed, but that can be something to look at later.  I'll submit a PR later tomorrow.

**Comment by zchee** [comment]
@tweekmonster Ok, Thanks. and looks forward to your PR.

BTW, Sorry for not good at English. I would like to confirm just in case, are you going to send the PR to Jedi? or deoplete-jedi or deoplete.nvim?

**Comment by tweekmonster** [comment]
Sorry, I'll be submitting to deoplete-jedi.  Jedi is too confusing to figure out in my spare time :sweat_smile: 

Some improvements I'll be making:

- Don't complete input that doesn't match `\w\._`.  Things like `# comment lines` were being passed to Jedi.  I don't know if this is a deoplete.nvim bug, but still should guard against it.
- Truncate module completions such as `os.pa` to `os`, `os.path.exi` to `os.path`, etc. to use as cache keys since Jedi doesn't filter module completions.  This means we don't need to call `jedi.Script()` for modules in `site-packages` more than once.

**Comment by zchee** [comment]
@tweekmonster Thanks for the detail.

> Don't complete input that doesn't match \w\._. Things like # comment lines were being passed to Jedi. I don't know if this is a deoplete.nvim bug, but still should guard against it.

Yes, It's known bug. but I was allowed to stand :sweat:

> Truncate module completions such as os.pa to os, os.path.exi to os.path, etc. to use as cache keys since Jedi doesn't filter module completions. This means we don't need to call jedi.Script() for modules in site-packages more than once.

Behavior and reason were I understand :)
but How do you implement? Already Will there has been such API is to Jedi?

**Comment by tweekmonster** [comment]
> Already Will there has been such API is to Jedi?

I looked through Jedi's cache source and docs a few days ago.  It looks like the cache is validated after a short period.  I don't think `site-packages` modules need to be revalidated at all.  I'm not sure if that's the problem or if it's the mixed virtualenvs.  From my tests, it seems like it's not using a cache at all.  I can test some more and verify if using a system installed Python version produces the same results as in the Docker image.

My other motivation for caching is because deoplete.nvim is async.  deoplete-jedi calls Jedi and then formats the results.  If the formatted results are cached, there will be less overhead for completion results.

Another possibility with keeping a local cache is returning stale results immediately and updating the cache in a thread if a project file has been changed.  That way, you get _something_ instead of a delay.

I'll submit a WIP PR shortly so you can see inspect it.

**Comment by zchee** [comment]
@tweekmonster Thanks PR :)
Move discussion to this PR.

**Comment by zchee** [comment]
@tony Now merged @tweekmonster caching feature.
Could you test it?

**Comment by sudip06** [comment]
I just installed jedi, youCompleteMe, nothing I can see in vim. Do I have to do something? I mean, how is this supposed to work? No documentation, alas!

**Comment by blueyed** [comment]
@sudip06 
You should provide more info, e.g. your (minimal) vimrc.
Also, please create a new issue, instead of commenting on an existing one.

**Comment by Shougo** [comment]
> I just installed jedi, youCompleteMe, nothing I can see in vim. Do I have to do something? 

You should create the issue for YouCompleteMe.
deoplete-jedi is not for YouCompleteMe extension.
