### ISSUE TITLE
Recommended Virtualenv Settings Require Package Duplication

### ISSUE THREAD

**Issue by tcuthbert** [zchee/deoplete-jedi#23]
# Problems summary
For every package I have installed in my app virtualenv I am required to also install in my nvim3 virtualenv.

## Expected
the nvim3 virtualenv should only be required to run the neovim python client and support importing of current virtualenv modules.

## Environment Information

 * OS: OSX
 * Neovim version: NVIM v0.1.3-61-gf03ab69

**Comment by tweekmonster** [comment]
@tcuthbert Do you mind elaborating?  Do you mean that completions don't appear for packages that are outside of your neovim virtualenv?  If so, can you confirm that the `VIRTUAL_ENV` is set and visible in Neovim?  `:echo $VIRTUAL_ENV`

Also, what is the Python version of virtualenv?

**Comment by tcuthbert** [comment]
Yes that is correct.

  

:echo $VIRTUAL_ENV returns nothing so I must be doing something wrong there.

  

I am using pyenv virtualenv.

  

I have also tried install vim-pyenv and running PyenvActivate to no avail :(

  

  

Regards,

  

Thomas Cuthbert

> On Mar 25 2016, at 5:04 am, Tommy Allen &lt;notifications@github.com&gt;
wrote:  

>

> [@tcuthbert](https://github.com/tcuthbert) Do you mind elaborating? Do you
mean that completions don't appear for packages that are outside of your
neovim virtualenv? If so, can you confirm that the VIRTUAL_ENV is set and
visible in Neovim? :echo $VIRTUAL_ENV

>

> Also, what is the Python version of virtualenv?

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/zchee
/deoplete-jedi/issues/23#issuecomment-201020217)![](https://github.com/notific
ations/beacon/AD64L-zKu3IwlIKurA5aTbHPG1tNq7Whks5pwvxIgaJpZM4H4T7a.gif)

**Comment by tweekmonster** [comment]
> :echo $VIRTUAL_ENV returns nothing so I must be doing something wrong there.

Yeah, if Jedi doesn't see that variable, it will use the current interpreter's site-packages.

> I am using pyenv virtualenv.

I'm by no means an expert with pyenv, but I will tell you what my workflow is and you can see if it remedies your problem:

- First, make sure pyenv is setup correctly: `which pyenv` should print a function, not a file path.  If it shows a file path, you did not complete the final step in setting up pyenv.
- Make sure that there is no pyenv shell version set: `pyenv shell --unset`
- Install the target version: `pyenv install 3.4.4`
- Create a virtualenv using that version: `pyenv virtualenv 3.4.4 myenv`
- Activate with: `pyenv activate myenv`

Doing that, I'm able to get the correct completions with deoplete-jedi.  When I'm working in a project (such as a Django project), I cd into the directory and run `pyenv local myenv` so that when I go to that directory to start nvim, the virtualenv is auto-activated.  It creates a `.python-version` file in that directory, so you would need an entry in the global gitignore file for it.

Another thing comes to mind: If you are using OS X and installed pyenv via homebrew, I recommend uninstalling it and using `pyenv-installer` instead.  The homebrew version installs the pyenv plugins separately and they can go out of sync with each other.  With `pyenv-installer` you run `pyenv update` occasionally and it will upgrade all plugins.

**Comment by tcuthbert** [comment]
Thanks for the update!

  

I have followed that process.

  

Am getting a return on that call

  

```

echo $VIRTUAL_ENV

/Users/tom/.pyenv/versions/trigger

```

  

In my nvim2 virtualenv I have kept everything brief so this is the output of
pip freeze

  

```

(nvim2)trigger ➤ pip freeze
git:textfsm*  
You are using pip version 6.0.8, however version 8.1.1 is available.  
You should consider upgrading via the 'pip install --upgrade pip' command.  
futures==3.0.5  
greenlet==0.4.9  
jedi==0.9.0  
msgpack-python==0.4.7  
neovim==0.1.5  
six==1.10.0  
trollius==2.1  
zope.interface==4.1.3  

```

  

My venv pip freeze output:

  

```

(trigger)trigger ➤ pip freeze
git:textfsm*  
You are using pip version 6.0.8, however version 8.1.1 is available.  
You should consider upgrading via the 'pip install --upgrade pip' command.  
crochet==1.4.0  
gtextfsm==0.2.1  
IPy==0.83  
pyasn1==0.1.9  
pycrypto==2.6.1  
pyparsing==1.5.7  
pytz==2016.3  
redis==2.10.5  
SimpleParse==2.2.0  
trigger==1.5.8  
Twisted==15.4.0  
zope.interface==4.1.3  

```

  

Still unable to complete twisted.

  

Regards,

  

Thomas Cuthbert

> On Mar 25 2016, at 5:25 am, Tommy Allen &lt;notifications@github.com&gt;
wrote:  

>

>> :echo $VIRTUAL_ENV returns nothing so I must be doing something wrong
there.

>

> Yeah, if Jedi doesn't see that variable, it will use the current
interpreter's site-packages.

>

>> I am using pyenv virtualenv.

>

> I'm by no means an expert with pyenv, but I will tell you what my workflow
is and you can see if it remedies your problem:

>

>   * First, make sure pyenv is setup correctly: which pyenv should print a
function, not a file path. If it shows a file path, you did not complete the
final step in setting up pyenv.

>   * Make sure that there is no pyenv shell version set: pyenv shell --unset

>   * Install the target version: pyenv install 3.4.4

>   * Create a virtualenv using that version: pyenv virtualenv 3.4.4 myenv

>   * Activate with: pyenv activate myenv

>

> Doing that, I'm able to get the correct completions with deoplete-jedi. When
I'm working in a project (such as a Django project), I cd into the directory
and run pyenv local myenv so that when I go to that directory to start nvim,
the virtualenv is auto-activated. It creates a .python-version file in that
directory, so you would need an entry in the global gitignore file for it.

>

> Another thing comes to mind: If you are using OS X and installed pyenv via
homebrew, I recommend uninstalling it and using pyenv-installer instead. The
homebrew version installs the pyenv plugins separately and they can go out of
sync with each other. With pyenv-installer you run pyenv update occasionally
and it will upgrade all plugins.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/zchee
/deoplete-jedi/issues/23#issuecomment-201028650)![](https://github.com/notific
ations/beacon/AD64LyOXFLo7M3-oU9vAk5jZo54ezv0Mks5pwwFRgaJpZM4H4T7a.gif)

**Comment by tweekmonster** [comment]
@tcuthbert Okay, I see what's going on now.  It looks like Jedi is not using the correct site-packages directory: https://github.com/davidhalter/jedi/blob/745184c63b56d1cdc2037b26754ad03088ea17e2/jedi/evaluate/sys_path.py#L34-L40

If the Python 3 version you have installed for neovim is 3.4, but your virtualenv is 2.7, the path comes out to: `~/.pyenv/versions/2.7.9/envs/jeditest/lib/python3.4/site-packages` (note the **python3.4** near the end).

I'm not sure if this is intentional.  But, it looks like it could also cause problems in Python 3 as well if the release versions are different.  I was able to do a quick fix to monkey patch `get_sys_path()` to the virtualenv's actual site-packages directory.  However, I think it may generate errors or simply not show completions for some packages if they are incompatible with Python 3.  You can try testing it to see if there are any problems: https://github.com/tweekmonster/deoplete-jedi/tree/jedi-monkeypatch

I tried it with a few packages and it seems to work.  But, I haven't had a need to use Python 2 in some time, so I don't feel my tests would be very exhaustive.  Something to note: it exclusively sets the virtualenv's site-packages.  I don't think I've seen a case for virtualenvs sharing packages with their source interpreter in a while.  But, something to keep in mind if you are doing that.

@zchee I think deoplete-jedi might need a server component that runs with the correct Python interpreter if the monkeypatch doesn't work.

**Comment by tcuthbert** [comment]
@tweekmonster I'm using your monkey-patch now and so far so good. I'll keep this issue update if I run into any problems.

**Comment by tweekmonster** [comment]
@tcuthbert I forgot to update that I know the reason why Jedi won't use a different version site-packages.  It's because it parses compiled modules.  It may cause a segfault when doing completions for those.  I think a server component would work best, but it will increase the complexity of this completer source.

**Comment by tcuthbert** [comment]
Hmm for what it's worth +1 for a server. I've discovered that imports don't work properly unless you are in a virtualenv.

**Comment by tweekmonster** [comment]
@tcuthbert Sorry for the delayed response.  Take a look at #29 to see a possible solution.

**Comment by zchee** [comment]
@tcuthbert I planned to merge to https://github.com/zchee/deoplete-jedi/pull/29.
Just a moments :)

**Comment by tcuthbert** [comment]
Hey not sure if you guys are across this

https://github.com/vheon/JediHTTP

I wonder if it could be adapted. Its what YCM currently uses.

**Comment by tweekmonster** [comment]
Yeah I saw that before, but it's a little too bulky for my liking.  I also wanted to avoid the complexity of needing to track a process that might've been forked in a separate nvim process.  I don't know if I'm overthinking it, but an HTTP layer with JSON serialization and HMAC signing would add to the latency, too.

**Comment by zchee** [comment]
@tcuthbert Sorry, It's issue automatically close by GitHub behavior.

I was merged that pull request.
Could you test latest `deoplete-jedi` master?
