### ISSUE TITLE
Completions don't work for python.django combined filetypes

### ISSUE THREAD

**Issue by monkoose** [zchee/deoplete-jedi#33]
# Problems summary
Seems like completions don't popup in `python.django` filetypes `autocmd BufNewFile,BufRead *.py setlocal filetype=python.django`
let g:loaded_deoplete_jedi returns 1, just doesn't complete.

Need confirmation. And don't know is this deoplete itself or deoplete-jedi.

## Expected
Competions should work in combined filetypes

## Environment Information

 * OS: Arch Linux
 * Neovim version: 0.1.3

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
autocmd BufNewFile,BufRead *.py setlocal filetype=python.django
```

**Comment by tweekmonster** [comment]
This is a limitation in deoplete.nvim: [deoplete.py#L105-L106](https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/deoplete.py#L105-L106)

Not sure if it was intentional.  What's your case for using multiple filetypes?  I have some plans for adding better support for Django, but most likely as a separate plugin.

**Comment by monkoose** [comment]
My case is to make django filetype snippets work in python files.
There is another solution to make this work with snippets-plugin, so this is not such a problem.

But my completions in `htmldjango.html` filetypes work for both django snippets and html omnifunc.

**Comment by tweekmonster** [comment]
Oh, so snippets.  I had this issue a while back.  Multiple filetypes seems to be supported by Vim, but only a handful of plugins actually recognize them.  I just made some autocmd's to deal with it.

```vim
autocmd BufNewFile,BufRead */templates/*.html setlocal filetype=htmldjango
autocmd FileType htmldjango,jinja UltiSnipsAddFiletypes html
```

I am making a plugin that helps with detection of Django project files because this is something that annoys the hell out of me.  Also, the fact that you can't get completions from `Whatever.objects.`

**Comment by JeanCoopengo** [comment]
@tweekmonster : I made a small test by patching the line you mentioned in deoplete, and it seems to work as expected. I will wait for an answer from Shougo on https://github.com/Shougo/deoplete.nvim/issues/258 , but I may propose a pull request if it it ok with him.

**Comment by tweekmonster** [comment]
@JeanCoopengo I'm on the fence for this issue because I don't know if this particular case is a fallacy.  Vim has builtin support for the `htmldjango` filetype.  There's also a builtin `django` syntax but only for templates so you can have highlighting for `markdown.django` and so on.  You can see them with `:!find $VIMRUNTIME -iname \*django\*`.  I feel that Vim's default handling of Django sucks, but it's not likely to change due to how old the runtime scripts are.

As a plugin developer, I don't know where the line is drawn.  If you have `python.django`, is it a template python script?  Should completions be given for template tags?  I'm inclined to say yes since that's what Vim implies.  In this case, deoplete.nvim should definitely support multiple filetypes.

I submitted a PR to fix the multiple filetypes.  But, my (off topic) opinion for this particular issue is that making `*.py` always use `python.django` isn't the way to go, and snippets auto-loading with the `django` filetype wasn't a great idea in hindsight.  `markdown.django` would give you syntax highlighting for template delimiters, but you'll also get snippets for markdown, and django models, forms and so on.  That doesn't make sense to me.  If you were really annoyed by this, you would end up with autocmds to *remove* the django snippets for `markdown.django`.

**Comment by JeanCoopengo** [comment]
@tweekmonster : I have worked on a plugin to manage [tryton](http://www.tryton.org/) projects. Basically, I need to extend the syntax and indentation rules for python files which are related to a tryton project.

I achieved that by extending the filetype of my python files and using custom syntax / indent files for the new extended type.

I consider that `python.trpy` files are `python` files with a bit of `tryton` in them. The main type is `python`, the second part could be seen as an extension of `python` in a specific context. So I expect everything that work in `python` files to be available in `python.trpy` files (including `jedi` :) ), as well as `tryton` specific behaviors.

Just my opinion though, I do not know how the builtin vim support of Django is designed, and my only experience with multiple types comes from working on one plugin.

**Comment by tweekmonster** [comment]
@JeanCoopengo `python.trpy` will work if the PR is accepted 🙂

I agree with your point.  My beef is with how Vim's core script is treating the `django` filetype as not-python but snippets are treating it as python.  By my reasoning, the filetype `python.django` is synonymous with `python.html`.

**Comment by JeanCoopengo** [comment]
@tweekmonster : I will test your PR :)

**Comment by tweekmonster** [comment]
@monkoose @JeanCoopengo I finally got around to making a plugin that helps with Django development: https://github.com/tweekmonster/django-plus.vim

If you are working in a Django project directory, you won't need the `python.django` filetype any longer.

**Comment by monkoose** [comment]
Thank you @tweekmonster 
Already got your plugin, but even without it seems like django snippets works fine in python files, atleast for me. Should have close this some time ago.
