### ISSUE TITLE
Use deoplete's logfile for the server

### ISSUE THREAD

**Issue by blueyed** [zchee/deoplete-jedi#74]
Instead of using `/tmp/jedi-server.log`, deoplete's logfile (from `call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')`) should be used also for the server.  `/tmp/jedi-server.log` would be the fallback then.

Maybe deoplete has to set some global var in Vim for the logfile location for this?!

**Comment by tweekmonster** [comment]
Ah yeah, this needs to happen (I also need to finish the new server).  I think it should be a separate file though since it's not sharing Deoplete's log setup.

**Comment by blueyed** [comment]
What I'm suggesting is to share the log setup though - not the handler object itself, but the file's location.

**Comment by tweekmonster** [comment]
I worry about the consistency of the messages.  But, I guess the formatter string can just be copied.  I can't do this now, but if you want to try, I think it should be as simple as changing the `--debug` flag to a string argument to pass the log file path.  Then changing it so that the path is passed through all of the classes [starting here](https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/deoplete_jedi.py#L63).
