### ISSUE TITLE
Add {rtp}/rplugin/python or python3 to jedi.settings.additional_dynamic_modules

### ISSUE THREAD

**Issue by lambdalisue** [zchee/deoplete-jedi#76]
### Summary

I would like to enable completion on modules in rplugins.

### Might help
https://github.com/lambdalisue/vim-ledi/blob/master/pythonx/ledi/util.py#L49

**Comment by tweekmonster** [comment]
What if there's a boolean option called `deoplete#sources#jedi#vim_plugin_dev`?  Then `$RUNTIMEPATH/rplugin` can be added to `sys.path`.

**Comment by blueyed** [comment]
FWIW: I've found that symlinking modules into `~/.vim/pythonx/` makes them available in Neovim/Vim, because of the special `'_vim_path_'` entry at the end of `sys.path`.
But this does not get picked up / used by the server probably?!

**Comment by tweekmonster** [comment]
@blueyed How does `_vim_path_` work?  I looked at the python client's source but it doesn't appear to do anything and I don't see anything in `sys.path` that relates to it.

In any case, I think the symlinking trick might be too obscure and not very portable.

**Comment by tweekmonster** [comment]
Actually, instead of a variable maybe it would be better if `rplugin/python{x,2,3}` exists (cwd), just add the directories in `&runtimepath` to `sys.path`

**Comment by tweekmonster** [comment]
@lambdalisue Could you try the `vim-dev` branch?  The paths should be added automatically if your `cwd` has a `rplugin/python*` directory.

**Comment by blueyed** [comment]
@tweekmonster 
It is handled through an import hook: https://github.com/neovim/python-client/blob/4dbfbd11a28b765a54928ebe6c6173c336ed841e/neovim/plugin/script_host.py#L228-L232 / https://github.com/neovim/python-client/blob/4dbfbd11a28b765a54928ebe6c6173c336ed841e/neovim/plugin/script_host.py#L237-L251.

But that is not used by the deoplete-jedi server.

But jedi-vim uses it, i.e. `<Ctrl-x><Ctrl-o>` (with `omnifunc=jedi#completions`) will use it for completions, but deoplete-jedi won't.

So, instead of manually adding `rplugin`, the same mechanism could/should be used in the server probably, which would make it behave like other clients/plugins?!

**Comment by tweekmonster** [comment]
WTF.  When I was searching the code for `VIM_SPECIAL_PATH` it only jumped between the `setup()` and `teardown()` function!  Maybe the code didn't load completely in my browser?

[It looks like that script is only for the `:python*` commands](https://github.com/neovim/neovim/blob/6e9f329d051cf6bf6d83dbe5335f86a1752ec45a/runtime/autoload/provider/python.vim#L30), though.  It could probably be used on the client side, but wouldn't work for the server since it would need to import from the `neovim` package.  The venv users won't have that, and injecting the client's `sys.path` into the server wouldn't work for Python 2.

The code in the `vim-dev` branch essentially does the same thing anyways, albeit less elegantly.

**Comment by blueyed** [comment]
Let's create a PR to discuss it?
https://github.com/zchee/deoplete-jedi/compare/vim-dev?expand=1

**Comment by tweekmonster** [comment]
I thought I created a PR 😱  I guess I commented instead.

**Comment by lambdalisue** [comment]
Thanks!
