### ISSUE TITLE
Don't block when doing from import expansion

### ISSUE THREAD

**Issue by purpleP** [zchee/deoplete-jedi#96]
# Problem summary
If I would type
`from some ` it will be replaced with
`from some import `
and then I can type what I want to import.

So the problem is that in large projects and large files if jedi doesn't have cache yet after I would type space after the word `some` neovim would be blocked and I would experience noticeable delay before neovim can response again to my typing.

I understand that parsing can be slow etc etc, but there's no reason to force me to wait for autocompletion.

From my observation I guess that deoplete-jedi doesn't let me type until it have completions for module that I'm trying to import, but at the same time without cache If I would type
`from functools` deoplete-jedi allows me to type even if it doesn't have completions yet and they starting to appear later. So I guess that kind of a bug.

**Comment by tweekmonster** [comment]
Deoplete only delays completions, it never blocks input.  If you have `jedi-vim` installed, you will need: `let g:jedi#completions_enabled = 0`

**Comment by purpleP** [comment]
@tweekmonster Yes, I have jedi-vim installed and yes I already have `let g:jedi#completions_enabled = 0`

**Comment by purpleP** [comment]
@tweekmonster Okay, I can't reproduce this behavior. I'll reopen the issue if this would happen again.

**Comment by tweekmonster** [comment]
@purpleP You can try clearing the cache in `~/.cache/deoplete/jedi` to see if the issue happens again.

**Comment by purpleP** [comment]
@tweekmonster Yeah, as I've said it only happens when there's no cache (more precisely I think when I open project for the first time). So I've already found `~/.cache/deoplete` and `~/.cache/jedi` and have been removing them on each try. It really looks like there is some hidden cache somewhere. Like maybe jedi process runs somewhere independently and stores it in memory or something.

**Comment by blueyed** [comment]
Sounds like jedi-vim's https://github.com/davidhalter/jedi-vim/blob/ef05bc402a5698ec3a33f8cfde645a38ccc1211c/ftplugin/python/jedi.vim#L40-L42.
It is not affected by the `g:jedi#completions_enabled = 0` switch AFAIK?! - but maybe should be?!

**Comment by tweekmonster** [comment]
> Sounds like jedi-vim's https://github.com/davidhalter/jedi-vim/blob/ef05bc402a5698ec3a33f8cfde645a38ccc1211c/ftplugin/python/jedi.vim#L40-L42.
It is not affected by the g:jedi#completions_enabled = 0 switch AFAIK?! - but maybe should be?!

I was just looking into this before you posted, but I got confused because I'm using the default settings.  It turns out my insert `<space>` map is used by the `auto-pairs` plugin so I wasn't affected.

It looks like this is the culprit.

Replying to @purpleP in case `let g:jedi#smart_auto_mappings = 0` doesn't work:

> Like maybe jedi process runs somewhere independently and stores it in memory or something.

The only cache that exists for deoplete-jedi is in `~/.cache/deoplete/jedi` and it's a cache that's incompatible with Jedi's.  deoplete-jedi disables Jedi's cache entirely and the completion server isn't forked, so it won't survive if the parent process dies.  I don't think the Jedi module factors into this.  You're restarting nvim after clearing the disk cache, right?

It's technically impossible for deoplete-jedi to block keyboard input in the nvim process.  The only way for it to block would be to call out to a Vim function from Python and deoplete-jedi doesn't do that.

**Comment by purpleP** [comment]
@blueyed @tweekmonster Okay, because of my previous fiddling with jedi-vim I know what's the problem was. I've defined jedi setttings like `g:jedi#completions_enabled` in my `after/python.vim` and I don't know why, but neovim (and vim probably too) loads jedi first and my settings later. I moved settings to vimrc and everything works smoothly now. Why is vim doing this?

**Comment by blueyed** [comment]
@purpleP 
I think `after/python.vim` should be `after/ftplugin/python.vim`, or `after/plugin/my-python.vim` to have a global plugin.  Try adding `echoerr "foo"` in there (`after/python.vim`), it is probably never sourced?!

**Comment by purpleP** [comment]
@blueyed  Yes, sorry, I meant `after/ftplugin/python.vim`. It is sourced.

**Comment by blueyed** [comment]
@purpleP 
It it probably to late there, since jedi-vim the setup already?!

**Comment by purpleP** [comment]
@blueyed well, obviously, but why Jedi sourced before my settings?

**Comment by blueyed** [comment]
`ftplugin` is handled when the filetype is handled (on-demand).
And even with `after/plugin/` you are doing your stuff explicitly _after_wards.. ;)
